In [1]:
import pandas as pd
import numpy as np

# Data Loading: Training Data

In [2]:
df_graduation = pd.read_excel("../dataset/Year of Graduation Data/Final Lead Data.xlsx")
df_graduation.head()

,ID,First Name,Email,Gender,City,Created,Position,New College Name,Colleges,Academic Year,Branch/ Specialisation,Other Branch,What is your current academic year?,Company Name/ College Name,Would you like to know more about us and our programs?,Are you interested in knowing more about our events?,Have you recommended Cloud Counselage to anyone?,How did you come to know about this event?
0,68112,ANIKET,aniket@xyz.com,NaN,NaN,04/27/2022 01:41:38 pm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,NaN
1,68110,Dhanshree,dhanshree@xyz.com,NaN,NaN,04/22/2022 04:08:38 pm,NaN,Lords Universal College,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,NaN
2,68108,Dhiraj,dhiraj@xyz.com,NaN,NaN,04/16/2022 10:31:59 pm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,NaN
3,68106,Pooja,pooja@xyz.com,NaN,NaN,04/13/2022 10:05:15 pm,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,NaN
4,68090,Aayush,aayush@xyz.com,NaN,NaN,03/26/2022 07:02:48 pm,NaN,B.k Birla college,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,NaN

In [3]:
df_graduation.shape

(5303, 18)

# Data Cleaning: Handle NA values

In [4]:
df_graduation.columns

Index(['ID', 'First Name', 'Email', 'Gender', 'City', 'Created', 'Position',
       'New College Name', 'Colleges', 'Academic Year',
       'Branch/ Specialisation', 'Other Branch',
       'What is your current academic year?', 'Company Name/ College Name',
       'Would you like to know more about us and our programs?',
       'Are you interested in knowing more about our events?',
       'Have you recommended Cloud Counselage to anyone?',
       'How did you come to know about this event?'],
      dtype='object')

In [5]:
df_graduation.isna().sum()

ID                                                           0
First Name                                                   0
Email                                                        0
Gender                                                    5103
City                                                      5248
Created                                                      0
Position                                                  5297
New College Name                                          3485
Colleges                                                  3622
Academic Year                                             2785
Branch/ Specialisation                                    2783
Other Branch                                              4659
What is your current academic year?                       5172
Company Name/ College Name                                5065
Would you like to know more about us and our programs?       0
Are you interested in knowing more about our events?         0
Have you recommended Cloud Counselage to anyone?             0
How did you come to know about this event?                5148
dtype: int64

In [6]:
df_graduation['Position'].unique()

array([nan, 'S.E.(C.E.)', 'S.Y(COMPUTER ENGG)',
       'S.Y(COMPUTER ENGINEERING)', 'T. Y. ( C. E.)',
       'T.Y. Computer Science', 'compter Engineering Third year'],
      dtype=object)

In [7]:
df_graduation['New College Name'].unique()

array([nan, 'Lords Universal College', 'B.k Birla college', ...,
       'Don Bosco college of engineering',
       'Don Bosco College of Engineering Margao',
       'Don Bosco College of Engineering, Fatorda, Margao'], dtype=object)

In [8]:
df_graduation['Colleges'].unique()

array([nan, 'Pune Institute of Computer Technology - PICT',
       "Bhavan's Sardar Patel Institute of Technology",
       'Cummins College of Engineering for Women',
       'Pimpri Chinchwad College of Engineering - PCCE',
       'Thadomal Shahani Engineering College',
       'KJ Somaiya College of Engineering', 'Others',
       'Maharashtra Institute of Technology - MIT',
       'Lokmanya Tilak College of Engineering',
       'Dr. Babasaheb Ambedkar Technological University - DBATU',
       'Sandip Institute of Technology and Research Center - SITRC',
       'Army Institute of Technology - AIT',
       'Indian Institute of Technology - IIT Bombay',
       'Government College of Engineering',
       'VIVA Institute of Technology',
       'Rajarshi Shahu College of Engineering - RSCE',
       'St. Francis Institute of Technology',
       'Government College of Engineering - Aurangabad',
       'SIES Graduate School of Technology',
       "Shivnagar Vidya Prasarak Mandal's College of Engineering",
       "P.E. Society's Modern College of Engineering",
       'Jayawantrao Sawant College of Engineering',
       "Nashik District Maratha Vidya Prasarak Samaj's K.B.T. College of Engineering",
       "All India Shri Shivaji Memorial Society's Institute of Information Technology - AISSMS",
       'Smt. Kashibai Navale College of Engineering - SKNCOE',
       'D.Y. Patil College of Engineering',
       'Walchand Institute of Technology - WIT',
       'Konkan Gyanpeeth College of Engineering',
       "SVKM's Dwarkadas J.Sanghvi College of Engineering",
       'Bharati Vidyapeeth College of Engineering',
       "Marathwada Mitra Mandal's College of Engineering - MMCOE",
       'Vidyalankar Institute of Technology - VIT',
       'Thakur College of Engineering and Technology',
       'N.B.N. Sinhgad School of Engineering - NBNSSOE',
       'Vishwakarma Institute of Information Technology',
       'AP Shah Institute of Technology - APSIT',
       'AG Patil Institute of Technology - AGPIT',
       'Atharva College of Engineering',
       'Mukesh Patel School of Technology Management and Engineering - MPSTME',
       'Maharashtra Academy of Engineering - MAE',
       'International Institute of Information Technology - IIIT Pune',
       'Sinhgad Academy of Engineering - SAE',
       'Narsee Monjee Institute of Management Studies - NMIMS University',
       'Fr. Conceicao Rodrigues College of Engineering',
       'GH Raisoni College of Engineering - GHRCE',
       'Watumal Institute of Electronics Engineering and Computer Technology',
       'St. John College of Enigneering and Technology',
       'Post Graduate Institute', 'Amity University - Mumbai',
       'Ajeenkya DY Patil University', 'Sanghavi College of Engineering',
       'Fr.C. Rodrigues Institute of Technology',
       'Shah and Anchor Kutchhi Engineering College - SAKEC',
       'Ramrao Adik Institute of Technology - RAIT',
       'Savitribai Phule Pune University',
       'Sinhgad Institute of Technology and Science - SITE',
       'College of Engineering - Pune',
       'Dr. D.Y. Patil College of Engineering',
       "GS Mandal's Marathwada Institute of Technology - MIT",
       "Vivekanand Education Society's Institute of Technology - VESIT",
       'Annasaheb Chudaman Patil College of Engineering - ACPCE',
       'Priyadarshini Institute of Engineering and Technology - PIET',
       'Priyadarshini J.L. College of Engineering - LTJSS',
       'Veermata Jijabai Technological Institute',
       'Don Bosco Institute of Technology',
       'Prof. Ram Meghe Institute of Technology and Research - RMITR',
       'Maharashtra College of Engineering - MCE',
       'Bharati Vidyapeeth University',
       'MIT College of Engineering - MITCOE',
       "Modern Education Society's Cusrow Wadia Institute of Technology",
       'GH Raisoni College of Engineering and Management - GHRCEM',
       'Shree LR Tiwari College of Engineering',
       'K.K. Wagh Institute of Engineering Education and Research',
       'Shri Ramdeobaba Kamla Nehru Engineering and Management College - RCOEM',
       'Suryodaya College of Engineering and Technology - SCET',
       'Pillai Institute of Information Technology, Engineering, Media Studies and Research',
       'Institute for Studies in Technology and Engineering',
       'Anjuman-I-Islam M.H. Saboo Siddik College of Engineering',
       'Dr. D.Y. Patil Vidyapeeth',
       'Rajiv Gandhi Institute of Technology',
       "Padmabhushan Vasantdada Patil Pratishthan's College of Engineering",
       'Sinhgad College of Engineering - SCOE',
       'Xavier Institute of Engineering',
       "ZES's Dnyanganga College of Engineering and Research - DCOER",
       "Modern Education Society's College of Engineering",
       'Theem College of Engineering',
       'R.M.D. Sinhgad School of Engineering - RMDSSOE',
       "Terna Public Charitable Trust's College of Engineering",
       'Terna Engineering College',
       'KJ Somaiya Institute of Engineering and Information Technology - KJSIEIT',
       'Sinhgad Institute of Technology',
       'Pillai HOC College of Engineering and Technology - PHCET',
       'Tatyasaheb Kore Institute of Engineering and Technology - TKIET',
       "Bharati Vidyapeeth's College of Engineering",
       'Vishwakarma Institute of Technology - VIT',
       'Datta Meghe College of Engineering',
       'Dr. D.Y. Patil School of Engineering',
       'Visvesaraya National Institute of Technology - VNIT Nagpur',
       'Institute of Information Technology',
       'Mahatma Gandhi Mission College of Engineering',
       'DG Ruparel College of Arts, Science and Commerce',
       'Rizvi College of Engineering',
       'D.Y. Patil College of Engineering and Technology',
       'Sipna College of Engineering and Technology - SCET',
       "Vidyavardhini's College of Engineering and Technology - VCET",
       'Pravara Ruralo Engineering College',
       'Vidarbha Institute of Technology - VIT',
       'Bharati Vidyapeeth Deemed University College of Engineering',
       "Pune Vidhyarthi Griha's College of Engineering and Technology - PVGCET",
       'M.S. Bidve Engineering College',
       "Mahatma Gandhi Mission's College of Engineering and Technology",
       'Priyadarshini College of Engineering - PCE',
       'Government College of Engineering and Research',
       'JSPM Narhe Technical Campus', "S.S.P.M.'s College of Engineering",
       'Shivajirao S.Jondhale College of Engineering',
       "JSPM's Bhivarabai Sawant Institute of Technology and Research for Women",
       'Deogiri Institute of Engineering and Management Studies - DIEMS',
       'Sharad Institute of Technology College of Engineering',
       'DY Patil University',
       "All India Shri Shivaji Memorial Society's College of Engineering - AISSMS",
       'KC College of Engineering and Management Studies and Research',
       'Indira College of Engineering and Management',
       'Sant Gadge Baba Amravati University',
       'Parvatibai Genba Moze College of Engineering - PGMCOE',
       'Symbiosis International University - SIU',
       'S.B. Jain Institute of Technology, Management and Research - SBJITMR',
       'Saraswati College of Engineering',
       'Smt. Bhagwati Chaturvedi College of Engineering',
       'Sant Gajanan Maharaj College of Engineering',
       'Shree Ramchandra College of Engineering - SRCOE',
       'Vidya Vikas Pratishthan Institute of Engineering and Technology',
       'MET Institute of Engineering',
       'Rajiv Gandhi College of Engineering and Research - RGCER',
       'Anjuman College of Engineering and Technology',
       'Shri Babulalji Agnihotri College of Engineering',
       'Dr. Babasaheb Ambedkar Marathwada University - BAMU',
       'N.K. Orchid College of Engineering and Technology',
       "Marathwada Mitra Mandal's Institute of Technology - MMIT",
       "Shrama Sadhana Bombay Trust's College of Engineering and Technology - SSCOET",
       'Pune District Education Association College of Engineering',
       'Smt. Indira Gandhi College of Engineering - SIGCE',
       'Genba Sopanrao Moze College of Engineering',
       'Shri Guru Gobind Singhji Institute of Engineering and Technology - SGGSCE&T',
       "D.K.T.E. Society's Textile and Engineering Institute",
       'Karmavir Dadasaheb Kannamwar College of Engineering - KDK',
       'GH Raisoni College of Engineering and Management',
       'Sri Sant Gajanan Maharaj College of Engineering - SSGMCE',
       'Usha Mittal Institute of Technology - UMIT',
       'Dhole Patil College of Engineering', 'Solapur University',
       'Yashwantrao Chavan Maharashtra Open University',
       'Prof. Ram Meghe College of Engineering and Management',
       'Datta Meghe Institute of Engineering Technology and Research - DMIETR',
       'P.E.S. College of Engineering',
       'Imperial College of Engineering and Research - ICOER',
       'Finolex Academy of Management and Technology',
       'Yashoda Shikshan Prasarak Mandal Yashoda Technical Campus',
       'Amrutvahini College of Engineering',
       "Mahatma Gandhi Mission's Jawaharlal Nehru Engineering College - MGM JNEC",
       'North Maharashtra University',
       'Shri Vithal Education and Research Institute College of Engineering - SVERI',
       "KCES'S College of Engineering and Information Technology",
       'Brahma Valley College of Engineering and Research Institute',
       'Alard College of Engineering and Management',
       'Walchand College of Engineering',
       'Padmabhooshan Vasantdada Patil Institute of Technology - PVPIT',
       'GH Raisoni Institute of Engineering and Technology for Women',
       "Bharati Vidyapeeth's College of Engineering for Women",
       "K.E. Society's Rajarambapu Institute of Technology",
       "Shreemati Nathibai Damodar Thackersey Women's University - Churchgate",
       "Kolhapur Institute of Technology's College of Engineering",
       'S.K.N. Sinhgad Institute of Technology and Science',
       'Annasaheb Dange College of Engineering and Technology - ADCET',
       'Yeshwantrao Chavan College of Engineering - YCCE',
       'Dr. Babasaheb Ambedkar College of Engineering and Research - DBACER',
       'Dr. JJ Magdum College of Engineering',
       'Shri Chhatrapati Shivaji Maharaj College of Engineering',
       'St. Vincent Pallotti College of Engineering and Technology',
       'Manoharbhai Patel Institute of Engineering and Technology - MIET',
       'Ballarpur Institute of Technology - BIT',
       'Government College of Engineering - GCE',
       'Padmashree Dr. D.Y. Patil Institute of Engineering and Technology',
       'Institute of Chemical Technology - ICT',
       'Jagadambha College of Engineering and Technology',
       'GH Raisoni Academy of Engineering and Technology',
       'Bhivarabai Sawant College of Engineering and Research - BSCER',
       'Wainganga College of Engineering and Management',
       'Matoshri College of Engineering and Research Center',
       'Tulsiramji Gaikwad-Patil College of Engineering and Technology (TGPCET)',
       'Siddhant College of Engineering',
       'Kavi Kulguru Institute of Technology and Science- KITS',
       'Late GN Sapkal College of Engineering',
       'Sanjivani College of Engineering',
       'Defence Institute of Advanced Technology - DIAT',
       'Shri Shankar Prasad Agnihotri College of Engineering - SSPACE',
       'JD College of Engineering and Management',
       'RC Patel Institute of Technology',
       'Yadavrao Tasgaonkar College of Engineering and Management - YTCEM',
       'Guru Nanak Institute of Engineering and Technology - GNIET',
       'Rashtrasant Tukadoji Maharaj Nagpur University - RTMNU',
       'S.N.D. College of Engineering and Research Centre - SNDCOERC',
       'Bapurao Deshmukh College of Engineering',
       'Padmabhooshan Vasantdada Patil Institute of Technology',
       'Mumbai Institute of Information Technology - MIIT',
       'Vidya Pratishthan’s College of Engineering - VPCE',
       'Rajendra Mane College of Engineering and Technology - RMCET',
       'Laxminarayan Institute of Technology'], dtype=object)

In [9]:
df_graduation['Academic Year'].unique()

array([nan,  3.,  2.,  1.,  4.])

In [10]:
df_graduation['Branch/ Specialisation'].unique()

array([nan, 'Information Technology (IT)', 'Other', 'Computer Science'],
      dtype=object)

In [11]:
df_graduation['Other Branch'].unique()

array([nan, 'Electronics', 'ETRX', 'Mechanical Engineering',
       'ELECTRONICS', 'Electronics Engineering', 'Computer Engineering',
       'Electronics and telecommunications', 'Mechanical engineering',
       'Production engineering', 'Electronics and telecommunication',
       'extc', 'Extc', 'EXTC', 'PHYSICS',
       'Electronic & telecommunication', 'SY BFM', 'B.sc', 'B.com',
       'SY BMS', 'TE COMPUTER ENGINEERING', 'Electrical', 'BMS', 'TYBCOM',
       'Electronics And telecommunication',
       'electronics and telecommunication',
       'Electronics & telecommunications',
       'Electronic and telecommunications engineering', 'physics',
       'AUTO MOBILE ENGINEERING', 'SYBA',
       'Electronics and Telecommunication', 'FYB.COM', 'Fybcom',
       'Electronics engineering', 'Electronic Engineering', 'D Pharma',
       'INSTRUMENTATION ENGINEERING', 'MECHANICAL', 'Mechanical',
       'Electroncis and Telecommunication',
       'Electronics and Telecommunication Engineering',
       'Computer technology', 'Biotechnology', 'Computer engineering',
       'Civil engineering', 'Commerce', 'mechanical engg',
       'Bachelor of arts', 'Electronics and Electrical Engineering',
       'Electronics & Telecommunication',
       'ELECTRONICS AND TELECOMMUICATION',
       'Computer Science & Engineering (Data Science)',
       'Electronics And Telecommunication',
       'ELECTRONICS AND TELECOMMUNICATION',
       'Electronic and Telecommunication',
       'Electronics and Telecommunication engineering',
       'CIVIL ENGINEERING', 'Electrical Engineering', 'Civil',
       'Electronics and Telecommunication (EXTC)', 'HR',
       'Computer Technology', 'ELECTRONIC AND TELECOMMUNICATIONS',
       'Civil Engineering', 'Mechatronics', 'Computer Application',
       'Computer Applications',
       'Electronics and Telecommunications (EXTC)',
       'Electronics and telecommunication engineering',
       'Electronics and Telecommunications',
       'Master of Computer Applications', 'Com',
       'ELECTRONICS & TELECOMMUNICATION OF ENGINEERING',
       'Mechatronics Engineering', 'Electronic and telecommunications',
       'Master Of Computer Applications', 'Management', 'Computer',
       'ELECTRONIC AND TELECOMMUNICATION',
       'Electronic and telecommunication', 'Production',
       'Production Engineering', 'Software', 'E&TC',
       'Electronics and Communications', 'Entc', 'Electrical engineering',
       'Electronic', 'HPCSA', 'Industrial and Management Engineering',
       'Big Data Analytics', 'Electrical Electronics and Power',
       'Mechanical Engg', 'Electronic engineering',
       'Cloud computing and information security',
       'Electronics and Instrumentation', 'Instrumentation engineering',
       'Electronic and Telecommunications',
       'electronics and telcommunicatio', 'Cyber security',
       'Chemical Engineering',
       'Electronics & Telecommunication Engineering',
       'Industrial Engineering and Management',
       'information security and cloud computing',
       'Post Graduate Program In Data Science and Engineering',
       'Cyber law and Information Security',
       'Instrumentation and control',
       'Electronics and tele. communications engineering',
       'Electronics and telecommunication department', 'MBA Finance',
       'electronics and telecommunication engineering', 'ECE',
       'Electronics and Computer Science',
       'Electronics and communication', 'ENTC',
       'Electronics and computer Science',
       'Electronics and Computer science', 'Materials Engineering',
       'E&Tc', 'MSc Industrial Mathematics with Computer Application',
       'PRODUCTION AND INDUSTRIAL ENGINEERING',
       'ELECTRONICS & TELECOMMUNICATION ENGINEERING',
       'electronics emgineering', 'electronics engineering',
       'ELECTRONICS AND TELECOMMUNICATION ENGINEERING', 'Data Science',
       'Statistics', 'Digital marketing',
       'Computer and communication engineering',
       'Computer programming language, networking',
       'Computer application', 'ETC',
       'Electronics and Communication Engineering', 'Economics',
       'Instrumentation and Control', 'electronics and te;ecommunication',
       'Eectronics & Communication', 'Petroleum Engineering',
       'Production processes', '-',
       'electronic and communication engineering', 'Instrumentation',
       'electronics & telecommunications',
       'Electronics & telecommunication engineering',
       'Accounting and Finance', 'Mechanical (Mechatronics)',
       'Electronics and telecommunications engineering',
       'Electrical and electronics engineering',
       'Electronic and communication', 'E&tc', 'PCM', 'Physics/maths',
       'aerospace engineering', 'PRODUCTION SANDWICH',
       'CHEMICAL TECHNOLOGY',
       'Electronic and telecommunication engineering', 'DATA SCIENCE',
       'Cloud technology and information security',
       'Electronics And Telecommunication Engineering', 'CAD/CAM',
       'Embedded and VLSI systems', 'Electronics And Telecommunications',
       'computer engineering', 'Computer EIGGERING',
       'Electronic and Telecommunication Engg.',
       'Electronic & Telecommunication',
       'Electronic and communication engineering',
       'mechanical engineering',
       'Fibres and Textile processing technology',
       'Electronic And Telecommunication', 'Design', 'Finance',
       'Electronics and Communication', 'Marketing',
       'ELECTRICAL AND ELECTRONICS ENGINEERING(EEE)', 'MINING', 'bba',
       'Electronicsand telecommunication', 'FOOD TECHNOLOGY',
       'Computer science specialization in Devops',
       'MSc Applied geophysics', 'Microbiology',
       'Material science and engineering', 'MECHANICAL ENGINEERING',
       'Electronics and telecom', 'Business Design Finance',
       'Industrial Engineering', 'elecrical engineering', 'Petroleum',
       'Machine Learning', 'Electronics and communication engineering',
       'Modelling and simulation',
       'Electronics and telecommunication Engineering', 'CS/IT',
       'Computer applications', 'Ece', 'Entc(artificial intelligence)',
       'Electronic communications', 'mechanical', 'CSIT', 'Aero',
       'Automobile', 'Cloud Technology and Information Security',
       'Metallurgical Engineering and Material Science',
       'Entrepreneurship Skills', 'Bioinformatics', 'EEE',
       'Mathematical Modeling & Simulation', 'Mathematics',
       'Electrical & Electronics'], dtype=object)

In [12]:
df_graduation['What is your current academic year?'].unique()

array([nan, 'Final Year', '1st Year', '2nd Year', '3rd Year'],
      dtype=object)

In [13]:
df_graduation['Company Name/ College Name'].unique()

array([nan, 'SRM Institute of science and technology, Chennai, India',
       'Reva university', 'Vidyalankar institute of Technology',
       'Engineering pte ltd',
       'B.K Birla College of Arts, Science and Commerce ,kalyan',
       'ARTISTIC ART FORUM P LTD',
       'International Institute of information technology Hinjawadi Pune I2IT',
       'Shaheed Sukhdev College of Business Studies',
       'Vidyalankar Institute of Technology',
       'Shri Shivaji law College, Parbhani', 'Y.T.I.E.T collage',
       'Y.T.I.E.T.,College, Karjat, Dist.Raigad',
       'Trinity College Dublin', 'Mit Academy of engineering, Pune',
       'MIT Academy of Engineering', 'B.K Birla college', 'NMIMS Mumbai',
       'Nowrosjee Wadia College Pune', 'Nowrosjee Wadia College, Pune',
       'St. Andrews College, Bandra', 'CMS B School, Bengaluru',
       'Sun International Institute of Tourism and Management',
       'MVSR Engineering College', 'IES MCRC',
       'Guru nanak khalsa college', 'NMIMS',
       'Institute of hotel management',
       'Swami Vivekanand Subharti University',
       'Nbn Sinhgad School Of Engineering, Pune.',
       'Massey University, New Zealand',
       'K. J . Somaiya College of Arts and Commerce',
       'Indira institute of management pune', 'Sri Sri University',
       'Don Bosco College, Kurla', 'Career Guidelines Limited',
       'Rizvi collage of science art and commerce',
       'Christ University Bangalore and Steinbeis University, Berlin',
       'DAYALBAGH EDUCATIONAL INSTITUTE', 'CRYSTAL HR', 'SIES College',
       'Delhi School of Economics, Delhi University',
       'Shri Ramdeobaba College of Engineering and Management, Nagur',
       'Yashoda Technical Campus', 'Vishwa Vishwani School of Business',
       'Vouchagram India Pvt.ltd', 'Jamia Millia Islamia',
       'K.J Somaiya college of engineering', 'B.K.Birla College, Kalyan',
       'BK Birla College, Kalyan', 'IHM Mumbai',
       'B. K. Birla College of Arts Commerce and Science',
       'B.K. Birla College of Arts Science and Commerce',
       'B.K. Birla College of Arts, Science & Commerce',
       'B.K. Birla College of Arts, Science & Commerce (Autonomous), Kalyan',
       'B. K. Birla College Kalyan',
       'B.K Birla College of Arts, Science and Commerce',
       'B.K.Birla college, kalyan', 'B.k Birla college',
       'B.K birla college of arts,commerce and science.',
       'BK birla college kalyan', 'B.k birla college',
       'Kamaladevi College', 'B. K. Birla college, kalyan',
       'Welingkar Institute of Management, Mumbai',
       'INSTITUTE OF PUBLIC ENTERPRISE',
       "Pillai College of Art's Commerce and Science, New Panvel",
       'RAJAGIRI CENTER FOR BUSINESS STUDIES', 'GLA University',
       'BK Birla college', 'Vidyalankar Institute of Technology, Mumbai',
       'Vidyalankar institute of technology',
       'Vidyalankar Institute Of Technology',
       'CHRIST (Deemed to be University), Bangalore',
       'M.H. Saboo Siddik College of Engineering', 'GSS HR Solutions',
       'Bosch Automotive Electronics',
       'Noida Institute of Engineering and Technology',
       'Nagpur University', 'Narayana Business School',
       'H.R. College, Mumbai', 'Prestige, Gwalior',
       'Mithibai college of arts', 'Sage University',
       'Ramrao Adik Institute of Technology',
       'MIT school of distance Education',
       'Thakur College of Science and Commerce',
       'Rajershi Shau College Latur',
       'Global Business School and Research centre, DPU', 'IISWBM',
       'Swami Keshvanand Institute of Technology',
       'Goa Institute of Management', 'Chandigarh University',
       'Sharda University', 'MIT WPU', 'Chandigarh university',
       'Vidyalankar Institute of Technology(VIT)',
       'P R Pote college of Engineering and management, Amravati',
       'Tolani College of commerce', 'Kelly Services',
       'Jain University, Bangalore', 'ghjcfjfd',
       'B.K Birla College Of Art, Commerce & Science',
       'L. D. College Of Engineering', 'ITM(SLS) Baroda University',
       'Aktu', 'Sequretek IT Solutions Pvt Ltd',
       'Welingkar Institute of Management',
       'Symbiosis Centre for Distance Learning (SCDL)',
       'M.L. Dahanukar College of Commerce (University of Mumbai)',
       'JK Business School', 'Bharti Vidyapeeth University',
       'MES College of Engineering, Kuttippuram',
       'Jaipur Engineering College & Research Centre', 'ResourceTree',
       'Welingkar institute', 'Jai Hind College',
       'Fr. C. Rodrigues Institute of Management Studies Vashi',
       'Manipal Health Enterprises Pvt Ltd', 'IIM Ranchi',
       'Kohinoor Business School', 'PENDAKANTI Institute of Management',
       'Mahatma phule Institute and management pune',
       'Doon Business school', 'Quality HR Services', 'MIT university',
       'IILM University Gurugram', 'CHANDIGARH UNIVERSITY',
       'K.C. College', 'Mumbai University', 'CDGI, Indore',
       'SCOE Kharghar', 'Jamnalal Bajaj Institute of Management Studies',
       'Pioneer Infotech Pvt Ltd', 'Kle hubbli', 'SIES College, Nerul',
       'Kohinoor business school', 'Bharti vidyapeeth deemed university',
       'Onsite Electro Service Pvt Ltd', 'IMIT', 'SK Somaiya College',
       'LinkedIn', 'A.C.Patil College of engineering', 'Tolani college',
       'Lakshmi Narain college of technology',
       'Dr. Vn bedekar Institute of Management Studies',
       'Dayalbagh Educational Institute,Agra',
       'Sri Ramachandra institute of higher education and research',
       'University of East Anglia',
       'Met institute of Computer science and technology', 'All You Need',
       'KJ Somaiya college of arts and commerce',
       'Sheila raheja business school', 'IIM Shillong', 'Whithat Jr',
       'Ramdeobaba College Of Engineering And Management', 'Mithibai',
       'Advocate', 'Mgvs Imr, Nashik', 'IIT KANPUR', 'Christ University',
       'LD college of engineering', 'HackerOne',
       'Walchand Institue Of Technology, Solapur',
       'Delhi Technological University', 'B. K. Birla college , Kalyan',
       'B.K. Birla College, Kalyan, Mumbai.', 'Birla College',
       'B.K.Birla Institute of Technology & Management Studies',
       'B. K. Birla college of science, commerce and arts',
       'B.K. Birla College, Kalyan',
       'K. J. Somaiya College of Engineering, Mumbai',
       'Pune institute of computer technology',
       'Pune Institute of Computer Technology',
       'Sinhgad Academy of Enginnering',
       'Vivekanand Education Society Institute of Technology',
       'S K Somaiya College',
       'shah and anchor kutchhi engineering college',
       'Shah and Anchor Kutchhi Engineering college chembur',
       'Lokmanya Tilak College of Enigneering', 'MPSTME, MUMBAI',
       'Walchand Institute of Technology Solapur',
       'Sinhgad College of Engineering, Vadgaon Bk, Pune', 'jdiet',
       "NMIMS' MPSTME", 'NMIMS MPSTME',
       'Narsee Monjee Institute of Management Studies',
       'Indian Institute of Technology (IIT) Kharagpur',
       'Mukesh Patel School of Technology Management and Engineering, NMIMS University',
       "NMIMS's MPSTME", 'MPSTME, NMIMS',
       'Mukesh Patel School of Technology Management and Engineering , NMIMS',
       'Implevision Technologies',
       'Alkesh Dinesh Mody Institute of Management Studies', 'TIMSCDR',
       'New Horizon Institute of technology and management',
       'Shri Pancham Khemraj Mahavidyalay', 'KTHM COLLEGE NASHIK',
       'M. H. Saboo Siddik College of Engineering',
       'vishwakarma college of arts commerce and science',
       'Kirti College', 'IIT Kanpur',
       'MARATHWADA INSTITUTE OF TECHNOLOGY',
       'Sri Sairam Institute of Technology',
       'Sinhgad College Of Engineering',
       'VIDYALANKAR INSTITUTE OF TECHNOLOGY', 'RAIT',
       'Priyadarshini Bhagwati College of Engineering',
       'Bharati vidyapeeth college of engineering',
       'MIT ACSC , Alandi Pune', 'NBN Sinhgad school of engineering',
       'St Miras College For Girls',
       'Parvatibai genba moze college of engineering wagholi pune.',
       'Model College, kalyan',
       'Thakur Institute of Management Studies, Career Development & Research',
       'Dr. Babasaheb Ambedkar Technological University Lonere Maharashtra'],
      dtype=object)

In [14]:
df_graduation['Would you like to know more about us and our programs?'].unique()

array(['yes', 'no'], dtype=object)

In [15]:
df_graduation['Are you interested in knowing more about our events?'].unique()

array(['yes', 'no'], dtype=object)

In [16]:
df_graduation['Have you recommended Cloud Counselage to anyone?'].unique()

array(['no', 'yes'], dtype=object)

In [17]:
df_graduation['How did you come to know about this event?'].unique()

array([nan, 'Whatsapp', 'Instagram', 'Other', 'LinkedIn', 'Facebook'],
      dtype=object)

In [18]:
# Convert 'Created' column to datetime
df_graduation['Created'] = pd.to_datetime(df_graduation['Created'], format='%m/%d/%Y %I:%M:%S %p')

# Extract the year and create a new column 'Created Year'
df_graduation['Created Year'] = df_graduation['Created'].dt.year

df_graduation.head()

,ID,First Name,Email,Gender,City,Created,Position,New College Name,Colleges,Academic Year,Branch/ Specialisation,Other Branch,What is your current academic year?,Company Name/ College Name,Would you like to know more about us and our programs?,Are you interested in knowing more about our events?,Have you recommended Cloud Counselage to anyone?,How did you come to know about this event?,Created Year
0,68112,ANIKET,aniket@xyz.com,NaN,NaN,2022-04-27 13:41:38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,NaN,2022
1,68110,Dhanshree,dhanshree@xyz.com,NaN,NaN,2022-04-22 16:08:38,NaN,Lords Universal College,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,NaN,2022
2,68108,Dhiraj,dhiraj@xyz.com,NaN,NaN,2022-04-16 22:31:59,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,NaN,2022
3,68106,Pooja,pooja@xyz.com,NaN,NaN,2022-04-13 22:05:15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,NaN,2022
4,68090,Aayush,aayush@xyz.com,NaN,NaN,2022-03-26 19:02:48,NaN,B.k Birla college,NaN,NaN,NaN,NaN,NaN,NaN,yes,yes,no,NaN,2022

In [19]:
df_graduation['Branch Names'] = df_graduation['Other Branch'].combine_first(df_graduation['Branch/ Specialisation'])
df_graduation['Branch Names'].unique()

array([nan, 'Information Technology (IT)', 'Electronics', 'ETRX',
       'Mechanical Engineering', 'ELECTRONICS', 'Electronics Engineering',
       'Computer Science', 'Computer Engineering',
       'Electronics and telecommunications', 'Mechanical engineering',
       'Production engineering', 'Electronics and telecommunication',
       'extc', 'Extc', 'EXTC', 'PHYSICS',
       'Electronic & telecommunication', 'SY BFM', 'B.sc', 'B.com',
       'SY BMS', 'TE COMPUTER ENGINEERING', 'Electrical', 'BMS', 'TYBCOM',
       'Electronics And telecommunication',
       'electronics and telecommunication',
       'Electronics & telecommunications',
       'Electronic and telecommunications engineering', 'physics',
       'AUTO MOBILE ENGINEERING', 'SYBA',
       'Electronics and Telecommunication', 'FYB.COM', 'Fybcom',
       'Electronics engineering', 'Electronic Engineering', 'D Pharma',
       'INSTRUMENTATION ENGINEERING', 'MECHANICAL', 'Mechanical',
       'Electroncis and Telecommunication',
       'Electronics and Telecommunication Engineering',
       'Computer technology', 'Biotechnology', 'Computer engineering',
       'Civil engineering', 'Commerce', 'mechanical engg',
       'Bachelor of arts', 'Electronics and Electrical Engineering',
       'Electronics & Telecommunication',
       'ELECTRONICS AND TELECOMMUICATION',
       'Computer Science & Engineering (Data Science)',
       'Electronics And Telecommunication',
       'ELECTRONICS AND TELECOMMUNICATION',
       'Electronic and Telecommunication',
       'Electronics and Telecommunication engineering',
       'CIVIL ENGINEERING', 'Electrical Engineering', 'Civil',
       'Electronics and Telecommunication (EXTC)', 'HR',
       'Computer Technology', 'ELECTRONIC AND TELECOMMUNICATIONS',
       'Civil Engineering', 'Mechatronics', 'Computer Application',
       'Computer Applications',
       'Electronics and Telecommunications (EXTC)',
       'Electronics and telecommunication engineering',
       'Electronics and Telecommunications',
       'Master of Computer Applications', 'Com',
       'ELECTRONICS & TELECOMMUNICATION OF ENGINEERING',
       'Mechatronics Engineering', 'Electronic and telecommunications',
       'Master Of Computer Applications', 'Management', 'Computer',
       'ELECTRONIC AND TELECOMMUNICATION',
       'Electronic and telecommunication', 'Production',
       'Production Engineering', 'Software', 'Other', 'E&TC',
       'Electronics and Communications', 'Entc', 'Electrical engineering',
       'Electronic', 'HPCSA', 'Industrial and Management Engineering',
       'Big Data Analytics', 'Electrical Electronics and Power',
       'Mechanical Engg', 'Electronic engineering',
       'Cloud computing and information security',
       'Electronics and Instrumentation', 'Instrumentation engineering',
       'Electronic and Telecommunications',
       'electronics and telcommunicatio', 'Cyber security',
       'Chemical Engineering',
       'Electronics & Telecommunication Engineering',
       'Industrial Engineering and Management',
       'information security and cloud computing',
       'Post Graduate Program In Data Science and Engineering',
       'Cyber law and Information Security',
       'Instrumentation and control',
       'Electronics and tele. communications engineering',
       'Electronics and telecommunication department', 'MBA Finance',
       'electronics and telecommunication engineering', 'ECE',
       'Electronics and Computer Science',
       'Electronics and communication', 'ENTC',
       'Electronics and computer Science',
       'Electronics and Computer science', 'Materials Engineering',
       'E&Tc', 'MSc Industrial Mathematics with Computer Application',
       'PRODUCTION AND INDUSTRIAL ENGINEERING',
       'ELECTRONICS & TELECOMMUNICATION ENGINEERING',
       'electronics emgineering', 'electronics engineering',
       'ELECTRONICS AND TELECOMMUNICATION ENGINEERING', 'Data Science',
       'Statistics', 'Digital marketing',
       'Computer and communication engineering',
       'Computer programming language, networking',
       'Computer application', 'ETC',
       'Electronics and Communication Engineering', 'Economics',
       'Instrumentation and Control', 'electronics and te;ecommunication',
       'Eectronics & Communication', 'Petroleum Engineering',
       'Production processes', '-',
       'electronic and communication engineering', 'Instrumentation',
       'electronics & telecommunications',
       'Electronics & telecommunication engineering',
       'Accounting and Finance', 'Mechanical (Mechatronics)',
       'Electronics and telecommunications engineering',
       'Electrical and electronics engineering',
       'Electronic and communication', 'E&tc', 'PCM', 'Physics/maths',
       'aerospace engineering', 'PRODUCTION SANDWICH',
       'CHEMICAL TECHNOLOGY',
       'Electronic and telecommunication engineering', 'DATA SCIENCE',
       'Cloud technology and information security',
       'Electronics And Telecommunication Engineering', 'CAD/CAM',
       'Embedded and VLSI systems', 'Electronics And Telecommunications',
       'computer engineering', 'Computer EIGGERING',
       'Electronic and Telecommunication Engg.',
       'Electronic & Telecommunication',
       'Electronic and communication engineering',
       'mechanical engineering',
       'Fibres and Textile processing technology',
       'Electronic And Telecommunication', 'Design', 'Finance',
       'Electronics and Communication', 'Marketing',
       'ELECTRICAL AND ELECTRONICS ENGINEERING(EEE)', 'MINING', 'bba',
       'Electronicsand telecommunication', 'FOOD TECHNOLOGY',
       'Computer science specialization in Devops',
       'MSc Applied geophysics', 'Microbiology',
       'Material science and engineering', 'MECHANICAL ENGINEERING',
       'Electronics and telecom', 'Business Design Finance',
       'Industrial Engineering', 'elecrical engineering', 'Petroleum',
       'Machine Learning', 'Electronics and communication engineering',
       'Modelling and simulation',
       'Electronics and telecommunication Engineering', 'CS/IT',
       'Computer applications', 'Ece', 'Entc(artificial intelligence)',
       'Electronic communications', 'mechanical', 'CSIT', 'Aero',
       'Automobile', 'Cloud Technology and Information Security',
       'Metallurgical Engineering and Material Science',
       'Entrepreneurship Skills', 'Bioinformatics', 'EEE',
       'Mathematical Modeling & Simulation', 'Mathematics',
       'Electrical & Electronics'], dtype=object)

In [20]:
df_graduation.isna().sum()

ID                                                           0
First Name                                                   0
Email                                                        0
Gender                                                    5103
City                                                      5248
Created                                                      0
Position                                                  5297
New College Name                                          3485
Colleges                                                  3622
Academic Year                                             2785
Branch/ Specialisation                                    2783
Other Branch                                              4659
What is your current academic year?                       5172
Company Name/ College Name                                5065
Would you like to know more about us and our programs?       0
Are you interested in knowing more about our events?         0
Have you recommended Cloud Counselage to anyone?             0
How did you come to know about this event?                5148
Created Year                                                 0
Branch Names                                              2783
dtype: int64

In [21]:
df_graduation['Academic Year'].unique()

array([nan,  3.,  2.,  1.,  4.])

In [22]:
# Filled nan values with '3'
df_graduation['Academic Year'].fillna(3, inplace=True)

In [23]:
# Renaming the column
df_graduation.rename(columns={'What is your current academic year?': 'Current Academic Year'}, inplace=True)
df_graduation['Current Academic Year'].unique()

array([nan, 'Final Year', '1st Year', '2nd Year', '3rd Year'],
      dtype=object)

In [24]:
df_graduation['Current Academic Year'] = df_graduation['Current Academic Year'].replace({
    'Final Year': 4,
    '1st Year': 1,
    '2nd Year': 2,
    '3rd Year': 3
})

# filled nan values with '1'
df_graduation['Current Academic Year'].fillna(1, inplace=True)
df_graduation['Current Academic Year'].unique()

array([1., 4., 2., 3.])

In [25]:
df_graduation.head()

,ID,First Name,Email,Gender,City,Created,Position,New College Name,Colleges,Academic Year,Branch/ Specialisation,Other Branch,Current Academic Year,Company Name/ College Name,Would you like to know more about us and our programs?,Are you interested in knowing more about our events?,Have you recommended Cloud Counselage to anyone?,How did you come to know about this event?,Created Year,Branch Names
0,68112,ANIKET,aniket@xyz.com,NaN,NaN,2022-04-27 13:41:38,NaN,NaN,NaN,3.0,NaN,NaN,1.0,NaN,yes,yes,no,NaN,2022,NaN
1,68110,Dhanshree,dhanshree@xyz.com,NaN,NaN,2022-04-22 16:08:38,NaN,Lords Universal College,NaN,3.0,NaN,NaN,1.0,NaN,yes,yes,no,NaN,2022,NaN
2,68108,Dhiraj,dhiraj@xyz.com,NaN,NaN,2022-04-16 22:31:59,NaN,NaN,NaN,3.0,NaN,NaN,1.0,NaN,yes,yes,no,NaN,2022,NaN
3,68106,Pooja,pooja@xyz.com,NaN,NaN,2022-04-13 22:05:15,NaN,NaN,NaN,3.0,NaN,NaN,1.0,NaN,yes,yes,no,NaN,2022,NaN
4,68090,Aayush,aayush@xyz.com,NaN,NaN,2022-03-26 19:02:48,NaN,B.k Birla college,NaN,3.0,NaN,NaN,1.0,NaN,yes,yes,no,NaN,2022,NaN

In [26]:
df_graduation.shape

(5303, 20)

In [27]:
df_graduation['Graduation Year'] = (df_graduation['Created Year']- df_graduation['Current Academic Year']) + df_graduation['Academic Year'] 

df_graduation['Graduation Year'] = df_graduation['Graduation Year'].astype(int)

df_graduation.head()

,ID,First Name,Email,Gender,City,Created,Position,New College Name,Colleges,Academic Year,...,Other Branch,Current Academic Year,Company Name/ College Name,Would you like to know more about us and our programs?,Are you interested in knowing more about our events?,Have you recommended Cloud Counselage to anyone?,How did you come to know about this event?,Created Year,Branch Names,Graduation Year
0,68112,ANIKET,aniket@xyz.com,NaN,NaN,2022-04-27 13:41:38,NaN,NaN,NaN,3.0,...,NaN,1.0,NaN,yes,yes,no,NaN,2022,NaN,2024
1,68110,Dhanshree,dhanshree@xyz.com,NaN,NaN,2022-04-22 16:08:38,NaN,Lords Universal College,NaN,3.0,...,NaN,1.0,NaN,yes,yes,no,NaN,2022,NaN,2024
2,68108,Dhiraj,dhiraj@xyz.com,NaN,NaN,2022-04-16 22:31:59,NaN,NaN,NaN,3.0,...,NaN,1.0,NaN,yes,yes,no,NaN,2022,NaN,2024
3,68106,Pooja,pooja@xyz.com,NaN,NaN,2022-04-13 22:05:15,NaN,NaN,NaN,3.0,...,NaN,1.0,NaN,yes,yes,no,NaN,2022,NaN,2024
4,68090,Aayush,aayush@xyz.com,NaN,NaN,2022-03-26 19:02:48,NaN,B.k Birla college,NaN,3.0,...,NaN,1.0,NaN,yes,yes,no,NaN,2022,NaN,2024

In [28]:
def calGraduationYear(createdYear, academicYear, currentAY):
    graduationY = (createdYear - currentAY) + academicYear
    
    return graduationY

In [29]:
calGraduationYear(2024, 4, 2)

2026

# Saving the result

In [30]:
file_path = 'graduation_prediction_result.xlsx'
df_graduation.to_excel(file_path, index=False)

print(f"DataFrame saved to {file_path}")

DataFrame saved to graduation_prediction_result.xlsx

In [31]:
import pandas as pd
import json

branch_names = df_graduation['Branch Names'].unique()

# Remove NaN values
branch_names = [branch for branch in branch_names if pd.notna(branch)]

# Define the filename
filename = 'branch_names.json'

# Write the list to a JSON file
with open(filename, 'w') as file:
    json.dump(branch_names, file)

print(f"Branch names saved to {filename}")

Branch names saved to branch_names.json